name: Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        # We use a dummy tag name since we aren't pushing it anywhere
        run: docker build . --file Dockerfile --tag local-check:latest